In [1]:
import pandas as pd
from pathlib import Path

# Define file paths
ZILLOW_PATH = Path("../data/raw/zillow/County_zhvi_uc_sfrcondo_tier_0.33_0.67_sm_sa_month.csv")
FEMA_PATH = Path("../data/raw/fema_nri/NRI_Table_Counties.csv")

# Load raw datasets
zhvi_data = pd.read_csv(ZILLOW_PATH)
nri_data = pd.read_csv(FEMA_PATH)

# Inspect basic structure
print("Zillow shape:", zhvi_data.shape)
print("FEMA NRI shape:", nri_data.shape)

print("\nZillow first rows:")
display(zhvi_data.head())

print("\nFEMA NRI first rows:")
display(nri_data.head())

Zillow shape: (3073, 322)
FEMA NRI shape: (3232, 465)

Zillow first rows:

,RegionID,SizeRank,RegionName,RegionType,StateName,State,Metro,StateCodeFIPS,MunicipalCodeFIPS,2000-01-31,...,2025-04-30,2025-05-31,2025-06-30,2025-07-31,2025-08-31,2025-09-30,2025-10-31,2025-11-30,2025-12-31,2026-01-31
0,3101,0,Los Angeles County,county,CA,CA,"Los Angeles-Long Beach-Anaheim, CA",6,37,207378.139086,...,867632.681133,862661.764204,858520.151316,856622.139882,856586.892712,858660.997572,861457.187977,864644.681242,868121.048715,869779.688397
1,139,1,Cook County,county,IL,IL,"Chicago-Naperville-Elgin, IL-IN-WI",17,31,145233.876893,...,305530.329774,305517.804006,305528.696370,306245.743513,307136.890573,308465.410472,309734.510842,311204.053706,312760.209619,314157.004441
2,1090,2,Harris County,county,TX,TX,"Houston-The Woodlands-Sugar Land, TX",48,201,110482.270951,...,281842.195255,280848.873550,279813.187274,278960.376724,278213.144299,277666.065467,277216.424846,276987.919005,277033.758614,276889.152202
3,2402,3,Maricopa County,county,AZ,AZ,"Phoenix-Mesa-Chandler, AZ",4,13,144511.068258,...,463419.137829,461388.955195,459510.628710,457492.403994,455839.626275,454769.654599,454342.106269,454563.676008,455339.961570,456184.043231
4,2841,4,San Diego County,county,CA,CA,"San Diego-Chula Vista-Carlsbad, CA",6,73,210703.817869,...,919396.983969,914664.101695,909523.902460,905227.788816,901869.469439,900047.881347,900016.924724,900997.603262,903114.130925,904312.219896

FEMA NRI first rows:

,OID_,NRI_ID,STATE,STATEABBRV,STATEFIPS,COUNTY,COUNTYTYPE,COUNTYFIPS,STCOFIPS,POPULATION,...,WNTW_EALS,WNTW_EALR,WNTW_ALRB,WNTW_ALRP,WNTW_ALRA,WNTW_ALR_NPCTL,WNTW_RISKV,WNTW_RISKS,WNTW_RISKR,NRI_VER
0,1,C01001,Alabama,AL,1,Autauga,County,1,1001,58764,...,13.095975,Very Low,2.198940e-07,5.442900e-09,1.423650e-06,27.739938,6928.050098,9.038829,Very Low,Dec-25
1,2,C01003,Alabama,AL,1,Baldwin,County,3,1003,231365,...,61.114551,Relatively Moderate,2.347150e-07,2.335050e-08,7.735080e-07,16.934985,92014.103472,59.325271,Relatively Low,Dec-25
2,3,C01005,Alabama,AL,1,Barbour,County,5,1005,25160,...,11.207430,Very Low,7.237260e-07,3.844440e-09,1.735310e-06,62.291022,9859.204661,11.807766,Very Low,Dec-25
3,4,C01007,Alabama,AL,1,Bibb,County,7,1007,22239,...,8.947368,Very Low,4.145820e-07,7.178340e-09,2.450400e-06,37.120743,5163.951371,6.938256,Very Low,Dec-25
4,5,C01009,Alabama,AL,1,Blount,County,9,1009,58992,...,21.486068,Relatively Low,2.598630e-07,1.426430e-08,1.670070e-06,27.337461,19317.477111,20.878421,Very Low,Dec-25

In [2]:
# Inspect Zillow dataset structure
print("Zillow shape:", zhvi_data.shape)

print("\nZillow data types:")
print(zhvi_data.info())

print("\nMissing values in Zillow dataset:")
print(zhvi_data.isnull().sum())

print("\nFirst 20 Zillow columns:")
print(zhvi_data.columns[:20])

print("\nFirst 5 rows of first 20 columns:")
display(zhvi_data.iloc[:5, :20])

Zillow shape: (3073, 322)

Zillow data types:
<class 'pandas.DataFrame'>
RangeIndex: 3073 entries, 0 to 3072
Columns: 322 entries, RegionID to 2026-01-31
dtypes: float64(313), int64(4), str(5)
memory usage: 7.5 MB
None

Missing values in Zillow dataset:
RegionID      0
SizeRank      0
RegionName    0
RegionType    0
StateName     0
             ..
2025-09-30    1
2025-10-31    0
2025-11-30    0
2025-12-31    0
2026-01-31    0
Length: 322, dtype: int64

First 20 Zillow columns:
Index(['RegionID', 'SizeRank', 'RegionName', 'RegionType', 'StateName',
       'State', 'Metro', 'StateCodeFIPS', 'MunicipalCodeFIPS', '2000-01-31',
       '2000-02-29', '2000-03-31', '2000-04-30', '2000-05-31', '2000-06-30',
       '2000-07-31', '2000-08-31', '2000-09-30', '2000-10-31', '2000-11-30'],
      dtype='str')

First 5 rows of first 20 columns:

,RegionID,SizeRank,RegionName,RegionType,StateName,State,Metro,StateCodeFIPS,MunicipalCodeFIPS,2000-01-31,2000-02-29,2000-03-31,2000-04-30,2000-05-31,2000-06-30,2000-07-31,2000-08-31,2000-09-30,2000-10-31,2000-11-30
0,3101,0,Los Angeles County,county,CA,CA,"Los Angeles-Long Beach-Anaheim, CA",6,37,207378.139086,207612.635194,208478.341339,210192.407160,212372.282337,214457.771337,216559.473385,218721.009194,220723.441249,222321.900262,223779.590344
1,139,1,Cook County,county,IL,IL,"Chicago-Naperville-Elgin, IL-IN-WI",17,31,145233.876893,145204.728456,145443.882970,146131.596540,147011.661937,147930.853623,148779.616722,149980.710437,151379.067376,153063.329983,154976.181895
2,1090,2,Harris County,county,TX,TX,"Houston-The Woodlands-Sugar Land, TX",48,201,110482.270951,110453.906109,110291.622694,110224.889777,110198.781715,110387.086653,110599.588742,110906.575211,111306.268492,111642.626562,112189.689200
3,2402,3,Maricopa County,county,AZ,AZ,"Phoenix-Mesa-Chandler, AZ",4,13,144511.068258,144805.816817,145195.297463,145995.986098,146878.661771,147626.681503,148371.660414,149066.388951,149848.678741,150574.782171,151306.279254
4,2841,4,San Diego County,county,CA,CA,"San Diego-Chula Vista-Carlsbad, CA",6,73,210703.817869,211538.050479,212549.254454,214838.853983,217312.031069,220423.632094,224001.284291,227926.184286,231625.282172,234782.607977,237862.975684

In [11]:
# Define target states for the current analysis
TARGET_STATES = ["FL"]

# Select identifier columns
identifier_columns = [
    "RegionID",
    "SizeRank",
    "RegionName",
    "State",
    "Metro",
    "StateCodeFIPS"
]

# Select monthly housing price columns from 2010 to 2025
monthly_columns = [
    col for col in zhvi_data.columns
    if len(col) >= 4 and '2010' <= col[:4] <= '2025'
]

# Combine identifier and monthly columns
required_columns = identifier_columns + monthly_columns

# Extract relevant Zillow data
zhvi_filtered = zhvi_data[required_columns]

# Filter Zillow data to target state(s)
zhvi_filtered = zhvi_filtered[
    zhvi_filtered["State"].isin(TARGET_STATES)
]

# Check output
print("Filtered Zillow shape:")
print(zhvi_filtered.shape)

print("\nTarget states included:")
print(zhvi_filtered["State"].unique())

print("\nNumber of counties/regions:")
print(zhvi_filtered["RegionID"].nunique())

print("\nDate range:")
print(monthly_columns[0], "to", monthly_columns[-1])

print("\nNumber of monthly columns:")
print(len(monthly_columns))

print("\nFiltered Zillow first rows:")
print(zhvi_filtered.head())

# Save the filtered Zillow data in the interim folder
zhvi_filtered.to_csv('../data/interim/filtered_zhvi_data.csv', index=False)

Filtered Zillow shape:
(67, 198)

Target states included:
<StringArray>
['FL']
Length: 1, dtype: str

Number of counties/regions:
67

Date range:
2010-01-31 to 2025-12-31

Number of monthly columns:
192

Filtered Zillow first rows:
    RegionID  SizeRank           RegionName State  \
7       2964         7    Miami-Dade County    FL
17      1561        17       Broward County    FL
25      2993        25    Palm Beach County    FL
27      3165        27  Hillsborough County    FL
28      1287        28        Orange County    FL

                                      Metro  StateCodeFIPS     2010-01-31  \
7   Miami-Fort Lauderdale-Pompano Beach, FL             12  174162.681875
17  Miami-Fort Lauderdale-Pompano Beach, FL             12  146697.046873
25  Miami-Fort Lauderdale-Pompano Beach, FL             12  176963.884806
27      Tampa-St. Petersburg-Clearwater, FL             12  142764.252688
28            Orlando-Kissimmee-Sanford, FL             12  151282.109366

       2010-02-28     2010-03-31     2010-04-30  ...     2025-03-31  \
7   172988.449635  172471.028917  172075.638411  ...  528765.539675
17  146969.177002  147372.081322  147318.679946  ...  440016.840949
25  176051.168639  175784.857854  175691.725482  ...  479675.448458
27  142264.605130  141957.890602  141441.907116  ...  384699.607715
28  149841.217796  148549.943611  147857.856904  ...  410198.793680

       2025-04-30     2025-05-31     2025-06-30     2025-07-31     2025-08-31  \
7   526247.609247  523184.385868  520306.468917  517235.136621  514709.734136
17  437602.166753  434479.523493  431275.544626  427670.231674  424825.718505
25  476710.066062  473514.088616  470205.719872  466273.804239  462759.374006
27  382756.400850  380649.023040  378391.915048  376037.653651  373835.644630
28  408340.557002  405964.718056  403398.989335  400742.475181  398515.597276

       2025-09-30     2025-10-31     2025-11-30     2025-12-31
7   513220.293607  512793.270562  512683.329238  512683.035117
17  422792.718204  421404.578917  419913.321124  418532.377334
25  460277.555596  459403.947418  459128.219098  459539.750425
27  372267.390999  371298.821359  370866.587040  370691.436167
28  397133.391933  396445.079913  396304.210165  396526.055502

[5 rows x 198 columns]

In [13]:
# Load the filtered Zillow dataset
filtered_zhvi_data = pd.read_csv("../data/interim/filtered_zhvi_data.csv")

# Reshape Zillow dataset from wide format to long format
zhvi_long = filtered_zhvi_data.melt(
    id_vars=["RegionID", "SizeRank", "RegionName", "State", "Metro", "StateCodeFIPS"],
    var_name="Date",
    value_name="HousingPrice"
)

# Convert Date column to datetime format
zhvi_long["Date"] = pd.to_datetime(zhvi_long["Date"], format="%Y-%m-%d")

# Sort data by county and date for panel time-series structure
zhvi_long = zhvi_long.sort_values(["RegionID", "Date"]).reset_index(drop=True)

# Inspect reshaped data
print("Reshaped Zillow shape:")
print(zhvi_long.shape)

print("\nDate range:")
print(zhvi_long["Date"].min(), "to", zhvi_long["Date"].max())

print("\nNumber of counties/regions:")
print(zhvi_long["RegionID"].nunique())

print("\nStates included:")
print(zhvi_long["State"].unique())

print("\nFirst rows:")
print(zhvi_long.head())

# Save reshaped Zillow dataset
zhvi_long.to_csv("../data/interim/reshaped_zhvi_data.csv", index=False)

Reshaped Zillow shape:
(12864, 8)

Date range:
2010-01-31 00:00:00 to 2025-12-31 00:00:00

Number of counties/regions:
67

States included:
<StringArray>
['FL']
Length: 1, dtype: str

First rows:
   RegionID  SizeRank  RegionName State            Metro  StateCodeFIPS  \
0        67       371  Bay County    FL  Panama City, FL             12
1        67       371  Bay County    FL  Panama City, FL             12
2        67       371  Bay County    FL  Panama City, FL             12
3        67       371  Bay County    FL  Panama City, FL             12
4        67       371  Bay County    FL  Panama City, FL             12

        Date   HousingPrice
0 2010-01-31  177323.256436
1 2010-02-28  175726.799272
2 2010-03-31  173648.913459
3 2010-04-30  172490.101014
4 2010-05-31  171749.827482

In [14]:
# Load the reshaped Zillow dataset
zhvi_long = pd.read_csv("../data/interim/reshaped_zhvi_data.csv")

# Check missing values
missing_values_zhvi = zhvi_long.isnull().sum()
print("Missing values in Zillow dataset:")
print(missing_values_zhvi)

# Check duplicate rows
duplicates_zhvi = zhvi_long.duplicated().sum()
print("\nNumber of duplicate rows in Zillow dataset:")
print(duplicates_zhvi)

Missing values in Zillow dataset:
RegionID            0
SizeRank            0
RegionName          0
State               0
Metro            3072
StateCodeFIPS       0
Date                0
HousingPrice       98
dtype: int64

Number of duplicate rows in Zillow dataset:
0

In [15]:
# Analyze missingness pattern in Zillow data

# 1. Total missing values
print("Missing values by column:")
print(zhvi_long.isnull().sum())

# 2. Percentage missing
missing_pct = zhvi_long.isnull().mean() * 100
print("\nMissing percentage by column:")
print(missing_pct)

# 3. Rows where HousingPrice is missing
missing_housing = zhvi_long[zhvi_long["HousingPrice"].isnull()]

print("\nNumber of missing HousingPrice rows:", len(missing_housing))
print("\nSample rows with missing HousingPrice:")
print(missing_housing.head())

# 4. Missing values by county
missing_by_county = (
    missing_housing.groupby("RegionName")
    .size()
    .sort_values(ascending=False)
)

print("\nMissing HousingPrice values by county:")
print(missing_by_county)

# 5. Missing values by date
missing_by_date = (
    missing_housing.groupby("Date")
    .size()
    .sort_values(ascending=False)
)

print("\nMissing HousingPrice values by date:")
print(missing_by_date)

Missing values by column:
RegionID            0
SizeRank            0
RegionName          0
State               0
Metro            3072
StateCodeFIPS       0
Date                0
HousingPrice       98
dtype: int64

Missing percentage by column:
RegionID          0.000000
SizeRank          0.000000
RegionName        0.000000
State             0.000000
Metro            23.880597
StateCodeFIPS     0.000000
Date              0.000000
HousingPrice      0.761816
dtype: float64

Number of missing HousingPrice rows: 98

Sample rows with missing HousingPrice:
      RegionID  SizeRank     RegionName State         Metro  StateCodeFIPS  \
1759       480      2056   Dixie County    FL           NaN             12
3840      1214       698  Monroe County    FL  Key West, FL             12
3841      1214       698  Monroe County    FL  Key West, FL             12
3842      1214       698  Monroe County    FL  Key West, FL             12
3843      1214       698  Monroe County    FL  Key West, FL             12

            Date  HousingPrice
1759  2012-08-31           NaN
3840  2010-01-31           NaN
3841  2010-02-28           NaN
3842  2010-03-31           NaN
3843  2010-04-30           NaN

Missing HousingPrice values by county:
RegionName
Monroe County        73
Liberty County       12
Washington County    12
Dixie County          1
dtype: int64

Missing HousingPrice values by date:
Date
2010-01-31    3
2010-02-28    3
2010-03-31    3
2010-04-30    3
2010-05-31    3
             ..
2015-09-30    1
2015-10-31    1
2015-11-30    1
2015-12-31    1
2016-01-31    1
Length: 73, dtype: int64

In [17]:
# Inspect Monroe County

monroe = zhvi_long[
    zhvi_long["RegionName"] == "Monroe County"
]

print(monroe.head(20))

print("\nFirst valid observation:")
print(
    monroe[
        monroe["HousingPrice"].notnull()
    ].head()
)

      RegionID  SizeRank     RegionName State         Metro  StateCodeFIPS  \
3840      1214       698  Monroe County    FL  Key West, FL             12
3841      1214       698  Monroe County    FL  Key West, FL             12
3842      1214       698  Monroe County    FL  Key West, FL             12
3843      1214       698  Monroe County    FL  Key West, FL             12
3844      1214       698  Monroe County    FL  Key West, FL             12
3845      1214       698  Monroe County    FL  Key West, FL             12
3846      1214       698  Monroe County    FL  Key West, FL             12
3847      1214       698  Monroe County    FL  Key West, FL             12
3848      1214       698  Monroe County    FL  Key West, FL             12
3849      1214       698  Monroe County    FL  Key West, FL             12
3850      1214       698  Monroe County    FL  Key West, FL             12
3851      1214       698  Monroe County    FL  Key West, FL             12
3852      1214       698  Monroe County    FL  Key West, FL             12
3853      1214       698  Monroe County    FL  Key West, FL             12
3854      1214       698  Monroe County    FL  Key West, FL             12
3855      1214       698  Monroe County    FL  Key West, FL             12
3856      1214       698  Monroe County    FL  Key West, FL             12
3857      1214       698  Monroe County    FL  Key West, FL             12
3858      1214       698  Monroe County    FL  Key West, FL             12
3859      1214       698  Monroe County    FL  Key West, FL             12

            Date  HousingPrice
3840  2010-01-31           NaN
3841  2010-02-28           NaN
3842  2010-03-31           NaN
3843  2010-04-30           NaN
3844  2010-05-31           NaN
3845  2010-06-30           NaN
3846  2010-07-31           NaN
3847  2010-08-31           NaN
3848  2010-09-30           NaN
3849  2010-10-31           NaN
3850  2010-11-30           NaN
3851  2010-12-31           NaN
3852  2011-01-31           NaN
3853  2011-02-28           NaN
3854  2011-03-31           NaN
3855  2011-04-30           NaN
3856  2011-05-31           NaN
3857  2011-06-30           NaN
3858  2011-07-31           NaN
3859  2011-08-31           NaN

First valid observation:
      RegionID  SizeRank     RegionName State         Metro  StateCodeFIPS  \
3913      1214       698  Monroe County    FL  Key West, FL             12
3914      1214       698  Monroe County    FL  Key West, FL             12
3915      1214       698  Monroe County    FL  Key West, FL             12
3916      1214       698  Monroe County    FL  Key West, FL             12
3917      1214       698  Monroe County    FL  Key West, FL             12

            Date   HousingPrice
3913  2016-02-29  491962.188031
3914  2016-03-31  495584.679629
3915  2016-04-30  499254.820330
3916  2016-05-31  506175.175922
3917  2016-06-30  511598.241002

In [18]:
# Find first available value for Monroe County

monroe = zhvi_long[
    zhvi_long["RegionName"] == "Monroe County"
]

print(
    monroe[
        monroe["HousingPrice"].notnull()
    ].head()
)

      RegionID  SizeRank     RegionName State         Metro  StateCodeFIPS  \
3913      1214       698  Monroe County    FL  Key West, FL             12
3914      1214       698  Monroe County    FL  Key West, FL             12
3915      1214       698  Monroe County    FL  Key West, FL             12
3916      1214       698  Monroe County    FL  Key West, FL             12
3917      1214       698  Monroe County    FL  Key West, FL             12

            Date   HousingPrice
3913  2016-02-29  491962.188031
3914  2016-03-31  495584.679629
3915  2016-04-30  499254.820330
3916  2016-05-31  506175.175922
3917  2016-06-30  511598.241002

In [19]:
# Missing value concentration by county

total_missing = missing_housing.shape[0]

missing_df = (
    missing_housing.groupby("RegionName")
    .size()
    .reset_index(name="MissingCount")
    .sort_values("MissingCount", ascending=False)
)

missing_df["Percentage"] = (
    missing_df["MissingCount"] / total_missing * 100
)

print(missing_df)

          RegionName  MissingCount  Percentage
2      Monroe County            73   74.489796
1     Liberty County            12   12.244898
3  Washington County            12   12.244898
0       Dixie County             1    1.020408

In [20]:
# Inspect Liberty County
liberty = zhvi_long[
    zhvi_long["RegionName"] == "Liberty County"
]

print("Liberty County (first 20 rows):")
print(liberty.head(20))

print("\nLiberty County missing rows:")
print(liberty[liberty["HousingPrice"].isnull()])


# Inspect Washington County
washington = zhvi_long[
    zhvi_long["RegionName"] == "Washington County"
]

print("\nWashington County (first 20 rows):")
print(washington.head(20))

print("\nWashington County missing rows:")
print(washington[washington["HousingPrice"].isnull()])

Liberty County (first 20 rows):
      RegionID  SizeRank      RegionName State Metro  StateCodeFIPS  \
6912      1858      2657  Liberty County    FL   NaN             12
6913      1858      2657  Liberty County    FL   NaN             12
6914      1858      2657  Liberty County    FL   NaN             12
6915      1858      2657  Liberty County    FL   NaN             12
6916      1858      2657  Liberty County    FL   NaN             12
6917      1858      2657  Liberty County    FL   NaN             12
6918      1858      2657  Liberty County    FL   NaN             12
6919      1858      2657  Liberty County    FL   NaN             12
6920      1858      2657  Liberty County    FL   NaN             12
6921      1858      2657  Liberty County    FL   NaN             12
6922      1858      2657  Liberty County    FL   NaN             12
6923      1858      2657  Liberty County    FL   NaN             12
6924      1858      2657  Liberty County    FL   NaN             12
6925      1858      2657  Liberty County    FL   NaN             12
6926      1858      2657  Liberty County    FL   NaN             12
6927      1858      2657  Liberty County    FL   NaN             12
6928      1858      2657  Liberty County    FL   NaN             12
6929      1858      2657  Liberty County    FL   NaN             12
6930      1858      2657  Liberty County    FL   NaN             12
6931      1858      2657  Liberty County    FL   NaN             12

            Date  HousingPrice
6912  2010-01-31           NaN
6913  2010-02-28           NaN
6914  2010-03-31           NaN
6915  2010-04-30           NaN
6916  2010-05-31           NaN
6917  2010-06-30           NaN
6918  2010-07-31           NaN
6919  2010-08-31           NaN
6920  2010-09-30           NaN
6921  2010-10-31           NaN
6922  2010-11-30           NaN
6923  2010-12-31           NaN
6924  2011-01-31  91348.727835
6925  2011-02-28  91134.221174
6926  2011-03-31  90719.444653
6927  2011-04-30  90152.244158
6928  2011-05-31  89718.251607
6929  2011-06-30  89701.694410
6930  2011-07-31  89620.930777
6931  2011-08-31  89989.167972

Liberty County missing rows:
      RegionID  SizeRank      RegionName State Metro  StateCodeFIPS  \
6912      1858      2657  Liberty County    FL   NaN             12
6913      1858      2657  Liberty County    FL   NaN             12
6914      1858      2657  Liberty County    FL   NaN             12
6915      1858      2657  Liberty County    FL   NaN             12
6916      1858      2657  Liberty County    FL   NaN             12
6917      1858      2657  Liberty County    FL   NaN             12
6918      1858      2657  Liberty County    FL   NaN             12
6919      1858      2657  Liberty County    FL   NaN             12
6920      1858      2657  Liberty County    FL   NaN             12
6921      1858      2657  Liberty County    FL   NaN             12
6922      1858      2657  Liberty County    FL   NaN             12
6923      1858      2657  Liberty County    FL   NaN             12

            Date  HousingPrice
6912  2010-01-31           NaN
6913  2010-02-28           NaN
6914  2010-03-31           NaN
6915  2010-04-30           NaN
6916  2010-05-31           NaN
6917  2010-06-30           NaN
6918  2010-07-31           NaN
6919  2010-08-31           NaN
6920  2010-09-30           NaN
6921  2010-10-31           NaN
6922  2010-11-30           NaN
6923  2010-12-31           NaN

Washington County (first 20 rows):
       RegionID  SizeRank         RegionName State Metro  StateCodeFIPS  \
11904      3050      1653  Washington County    FL   NaN             12
11905      3050      1653  Washington County    FL   NaN             12
11906      3050      1653  Washington County    FL   NaN             12
11907      3050      1653  Washington County    FL   NaN             12
11908      3050      1653  Washington County    FL   NaN             12
11909      3050      1653  Washington County    FL   NaN             12
11910      3050      1653  Washington County    FL   NaN             12
11911      3050      1653  Washington County    FL   NaN             12
11912      3050      1653  Washington County    FL   NaN             12
11913      3050      1653  Washington County    FL   NaN             12
11914      3050      1653  Washington County    FL   NaN             12
11915      3050      1653  Washington County    FL   NaN             12
11916      3050      1653  Washington County    FL   NaN             12
11917      3050      1653  Washington County    FL   NaN             12
11918      3050      1653  Washington County    FL   NaN             12
11919      3050      1653  Washington County    FL   NaN             12
11920      3050      1653  Washington County    FL   NaN             12
11921      3050      1653  Washington County    FL   NaN             12
11922      3050      1653  Washington County    FL   NaN             12
11923      3050      1653  Washington County    FL   NaN             12

             Date  HousingPrice
11904  2010-01-31           NaN
11905  2010-02-28           NaN
11906  2010-03-31           NaN
11907  2010-04-30           NaN
11908  2010-05-31           NaN
11909  2010-06-30           NaN
11910  2010-07-31           NaN
11911  2010-08-31           NaN
11912  2010-09-30           NaN
11913  2010-10-31           NaN
11914  2010-11-30           NaN
11915  2010-12-31           NaN
11916  2011-01-31  85448.687785
11917  2011-02-28  85037.665344
11918  2011-03-31  84551.848280
11919  2011-04-30  83741.424445
11920  2011-05-31  83157.356296
11921  2011-06-30  83334.498172
11922  2011-07-31  83752.050396
11923  2011-08-31  84382.740017

Washington County missing rows:
       RegionID  SizeRank         RegionName State Metro  StateCodeFIPS  \
11904      3050      1653  Washington County    FL   NaN             12
11905      3050      1653  Washington County    FL   NaN             12
11906      3050      1653  Washington County    FL   NaN             12
11907      3050      1653  Washington County    FL   NaN             12
11908      3050      1653  Washington County    FL   NaN             12
11909      3050      1653  Washington County    FL   NaN             12
11910      3050      1653  Washington County    FL   NaN             12
11911      3050      1653  Washington County    FL   NaN             12
11912      3050      1653  Washington County    FL   NaN             12
11913      3050      1653  Washington County    FL   NaN             12
11914      3050      1653  Washington County    FL   NaN             12
11915      3050      1653  Washington County    FL   NaN             12

             Date  HousingPrice
11904  2010-01-31           NaN
11905  2010-02-28           NaN
11906  2010-03-31           NaN
11907  2010-04-30           NaN
11908  2010-05-31           NaN
11909  2010-06-30           NaN
11910  2010-07-31           NaN
11911  2010-08-31           NaN
11912  2010-09-30           NaN
11913  2010-10-31           NaN
11914  2010-11-30           NaN
11915  2010-12-31           NaN

In [21]:
# Load reshaped Zillow data
zhvi_long = pd.read_csv("../data/interim/reshaped_zhvi_data.csv")

# Convert Date to datetime
zhvi_long["Date"] = pd.to_datetime(zhvi_long["Date"])

# Sort data by county and date
zhvi_long = zhvi_long.sort_values(
    by=["RegionID", "Date"]
).reset_index(drop=True)

# Keep rows from the first valid HousingPrice onward for each county
zhvi_long["valid_started"] = (
    zhvi_long
    .groupby("RegionID")["HousingPrice"]
    .transform(lambda x: x.notna().cummax())
)

trimmed_data = zhvi_long[zhvi_long["valid_started"]].copy()

# Drop helper column
trimmed_data = trimmed_data.drop(columns=["valid_started"])

# Check remaining missing rows
remaining_missing = trimmed_data[trimmed_data["HousingPrice"].isnull()]
print("Remaining missing rows:")
print(remaining_missing)

# Interpolate isolated internal missing values within each county
trimmed_data["HousingPrice"] = (
    trimmed_data
    .groupby("RegionID")["HousingPrice"]
    .transform(lambda x: x.interpolate(method="linear"))
)

# Re-sort final data
trimmed_data = trimmed_data.sort_values(
    by=["RegionID", "Date"]
).reset_index(drop=True)

# Final checks
print("Final shape:", trimmed_data.shape)

print("\nMissing values after final cleaning:")
print(trimmed_data.isnull().sum())

print("\nColumns:")
print(trimmed_data.columns)

# Save cleaned data
trimmed_data.to_csv("../data/interim/cleaned_florida_zhvi_data.csv", index=False)

Remaining missing rows:
      RegionID  SizeRank    RegionName State Metro  StateCodeFIPS       Date  \
1759       480      2056  Dixie County    FL   NaN             12 2012-08-31

      HousingPrice
1759           NaN
Final shape: (12767, 8)

Missing values after final cleaning:
RegionID            0
SizeRank            0
RegionName          0
State               0
Metro            3048
StateCodeFIPS       0
Date                0
HousingPrice        0
dtype: int64

Columns:
Index(['RegionID', 'SizeRank', 'RegionName', 'State', 'Metro', 'StateCodeFIPS',
       'Date', 'HousingPrice'],
      dtype='str')

In [22]:
# =========================
# Final Data Quality Checks
# =========================

# 1. Check for duplicate rows
duplicates = trimmed_data.duplicated().sum()
print(f"Number of duplicate rows: {duplicates}")

# 2. Check for invalid housing prices (<= 0)
invalid_prices = trimmed_data[trimmed_data["HousingPrice"] <= 0]
print(f"\nNumber of invalid (<=0) housing prices: {len(invalid_prices)}")

# 3. Summary statistics
print("\nHousing Price Summary:")
print(trimmed_data["HousingPrice"].describe())

# 4. Check time continuity within each county
date_diffs = trimmed_data.groupby("RegionID")["Date"].diff()

print("\nDate difference distribution (should mostly be ~30/31 days):")
print(date_diffs.value_counts().head())

# 5. Check number of unique counties
num_counties = trimmed_data["RegionID"].nunique()
print(f"\nNumber of unique counties: {num_counties}")

# 6. Metro missing values (expected)
print("\nMetro missing values:")
print(trimmed_data["Metro"].isnull().sum())

# 7. Final sorting
trimmed_data = trimmed_data.sort_values(
    by=["RegionID", "Date"]
).reset_index(drop=True)

print("\nFinal dataset shape:", trimmed_data.shape)

# 8. Final column check
print("\nColumns:")
print(trimmed_data.columns)

Number of duplicate rows: 0

Number of invalid (<=0) housing prices: 0

Housing Price Summary:
count    1.276700e+04
mean     2.108995e+05
std      1.173361e+05
min      6.831907e+04
25%      1.265801e+05
50%      1.819608e+05
75%      2.639765e+05
max      1.001663e+06
Name: HousingPrice, dtype: float64

Date difference distribution (should mostly be ~30/31 days):
Date
31 days    7381
30 days    4256
28 days     797
29 days     266
Name: count, dtype: int64

Number of unique counties: 67

Metro missing values:
3048

Final dataset shape: (12767, 8)

Columns:
Index(['RegionID', 'SizeRank', 'RegionName', 'State', 'Metro', 'StateCodeFIPS',
       'Date', 'HousingPrice'],
      dtype='str')

In [23]:
# Load FEMA NRI dataset
fema_data = pd.read_csv("../data/raw/fema_nri/NRI_Table_Counties.csv")

# Basic inspection
print("Shape:", fema_data.shape)

print("\nColumns:")
print(fema_data.columns)

print("\nFirst few rows:")
print(fema_data.head())

print("\nData types:")
print(fema_data.info())

Shape: (3232, 465)

Columns:
Index(['OID_', 'NRI_ID', 'STATE', 'STATEABBRV', 'STATEFIPS', 'COUNTY',
       'COUNTYTYPE', 'COUNTYFIPS', 'STCOFIPS', 'POPULATION',
       ...
       'WNTW_EALS', 'WNTW_EALR', 'WNTW_ALRB', 'WNTW_ALRP', 'WNTW_ALRA',
       'WNTW_ALR_NPCTL', 'WNTW_RISKV', 'WNTW_RISKS', 'WNTW_RISKR', 'NRI_VER'],
      dtype='str', length=465)

First few rows:
   OID_  NRI_ID    STATE STATEABBRV  STATEFIPS   COUNTY COUNTYTYPE  \
0     1  C01001  Alabama         AL          1  Autauga     County
1     2  C01003  Alabama         AL          1  Baldwin     County
2     3  C01005  Alabama         AL          1  Barbour     County
3     4  C01007  Alabama         AL          1     Bibb     County
4     5  C01009  Alabama         AL          1   Blount     County

   COUNTYFIPS  STCOFIPS  POPULATION  ...  WNTW_EALS            WNTW_EALR  \
0           1      1001       58764  ...  13.095975             Very Low
1           3      1003      231365  ...  61.114551  Relatively Moderate
2           5      1005       25160  ...  11.207430             Very Low
3           7      1007       22239  ...   8.947368             Very Low
4           9      1009       58992  ...  21.486068       Relatively Low

      WNTW_ALRB     WNTW_ALRP     WNTW_ALRA WNTW_ALR_NPCTL    WNTW_RISKV  \
0  2.198940e-07  5.442900e-09  1.423650e-06      27.739938   6928.050098
1  2.347150e-07  2.335050e-08  7.735080e-07      16.934985  92014.103472
2  7.237260e-07  3.844440e-09  1.735310e-06      62.291022   9859.204661
3  4.145820e-07  7.178340e-09  2.450400e-06      37.120743   5163.951371
4  2.598630e-07  1.426430e-08  1.670070e-06      27.337461  19317.477111

   WNTW_RISKS      WNTW_RISKR  NRI_VER
0    9.038829        Very Low   Dec-25
1   59.325271  Relatively Low   Dec-25
2   11.807766        Very Low   Dec-25
3    6.938256        Very Low   Dec-25
4   20.878421        Very Low   Dec-25

[5 rows x 465 columns]

Data types:
<class 'pandas.DataFrame'>
RangeIndex: 3232 entries, 0 to 3231
Columns: 465 entries, OID_ to NRI_VER
dtypes: float64(396), int64(5), str(64)
memory usage: 11.5 MB
None

In [24]:
# Define target states for the current analysis
TARGET_STATES = ["FL"]

# Select FEMA identifier columns
# STCOFIPS will later be used as the merge key with Zillow
# COUNTY is retained temporarily for validation and sanity checks
IDENTIFIER_COLUMNS = [
    "STATE",
    "STATEABBRV",
    "COUNTY",
    "STCOFIPS"
]

# Select baseline control variables
# POPULATION captures housing demand and county size
BASELINE_COLUMNS = [
    "POPULATION"
]

# Select climate risk variables
# CFLD_RISKS  -> Coastal Flood Risk
# HRCN_RISKS  -> Hurricane Risk
# SOVI_SCORE  -> Social Vulnerability
# RESL_SCORE  -> Community Resilience
CLIMATE_COLUMNS = [
    "CFLD_RISKS",
    "HRCN_RISKS",
    "SOVI_SCORE",
    "RESL_SCORE"
]

# Combine all required FEMA columns
required_columns = (
    IDENTIFIER_COLUMNS
    + BASELINE_COLUMNS
    + CLIMATE_COLUMNS
)

# Extract relevant FEMA data
fema_filtered = fema_data[required_columns]

# Filter FEMA data to target state(s)
fema_filtered = fema_filtered[
    fema_filtered["STATEABBRV"].isin(TARGET_STATES)
]

# Check output
print("Filtered FEMA shape:")
print(fema_filtered.shape)

print("\nStates included:")
print(fema_filtered["STATEABBRV"].unique())

print("\nNumber of counties:")
print(fema_filtered["STCOFIPS"].nunique())

print("\nColumns:")
print(fema_filtered.columns)

print("\nFirst rows:")
print(fema_filtered.head())

# Save filtered FEMA dataset in the interim folder
fema_filtered.to_csv(
    "../data/interim/filtered_fema_data.csv",
    index=False
)

Filtered FEMA shape:
(67, 9)

States included:
<StringArray>
['FL']
Length: 1, dtype: str

Number of counties:
67

Columns:
Index(['STATE', 'STATEABBRV', 'COUNTY', 'STCOFIPS', 'POPULATION', 'CFLD_RISKS',
       'HRCN_RISKS', 'SOVI_SCORE', 'RESL_SCORE'],
      dtype='str')

First rows:
       STATE STATEABBRV    COUNTY  STCOFIPS  POPULATION  CFLD_RISKS  \
313  Florida         FL   Alachua     12001      277984         0.0
314  Florida         FL     Baker     12003       27852         0.0
315  Florida         FL       Bay     12005      174869        77.2
316  Florida         FL  Bradford     12007       28233         0.0
317  Florida         FL   Brevard     12009      606067        82.0

     HRCN_RISKS  SOVI_SCORE  RESL_SCORE
313   96.704214   34.764631   80.979644
314   74.468085   24.427481   71.787532
315   98.664998   30.852417   29.452926
316   87.567793   48.314249   37.913486
317   99.707968   40.839695   63.358779

In [25]:
# Load filtered FEMA dataset
fema_filtered = pd.read_csv("../data/interim/filtered_fema_data.csv")

# Check missing values
missing_values_fema = fema_filtered.isnull().sum()

print("Missing values in FEMA dataset:")
print(missing_values_fema)

# Check duplicate rows
duplicates_fema = fema_filtered.duplicated().sum()

print("\nNumber of duplicate rows:")
print(duplicates_fema)

Missing values in FEMA dataset:
STATE         0
STATEABBRV    0
COUNTY        0
STCOFIPS      0
POPULATION    0
CFLD_RISKS    8
HRCN_RISKS    0
SOVI_SCORE    0
RESL_SCORE    0
dtype: int64

Number of duplicate rows:
0

In [26]:
# Inspect counties with missing Coastal Flood Risk

missing_cfld = fema_filtered[
    fema_filtered["CFLD_RISKS"].isnull()
]

print("Number of counties with missing CFLD_RISKS:")
print(len(missing_cfld))

print("\nCounties with missing CFLD_RISKS:")
print(
    missing_cfld[
        ["COUNTY", "STCOFIPS", "CFLD_RISKS"]
    ]
)

Number of counties with missing CFLD_RISKS:
8

Counties with missing CFLD_RISKS:
       COUNTY  STCOFIPS  CFLD_RISKS
18    Gadsden     12039         NaN
22   Hamilton     12047         NaN
26  Highlands     12055         NaN
30    Jackson     12063         NaN
38    Madison     12079         NaN
48    Osceola     12097         NaN
52       Polk     12105         NaN
59     Sumter     12119         NaN

In [27]:
# Compare missing and non-missing Coastal Flood Risk counties

print("Counties with missing CFLD_RISKS:")
print(
    fema_filtered[
        fema_filtered["CFLD_RISKS"].isnull()
    ][["COUNTY", "CFLD_RISKS"]]
)

print("\nSummary of non-missing CFLD_RISKS:")
print(
    fema_filtered["CFLD_RISKS"].describe()
)

Counties with missing CFLD_RISKS:
       COUNTY  CFLD_RISKS
18    Gadsden         NaN
22   Hamilton         NaN
26  Highlands         NaN
30    Jackson         NaN
38    Madison         NaN
48    Osceola         NaN
52       Polk         NaN
59     Sumter         NaN

Summary of non-missing CFLD_RISKS:
count    59.000000
mean     54.271186
std      35.941787
min       0.000000
25%      22.900000
50%      65.200000
75%      87.000000
max      99.600000
Name: CFLD_RISKS, dtype: float64

In [28]:
# Look at all Coastal Flood variables

cfld_cols = [col for col in fema_data.columns if "CFLD" in col]

print(cfld_cols)

['CFLD_EVNTS', 'CFLD_AFREQ', 'CFLD_EXP_AREA', 'CFLD_EXPB', 'CFLD_EXPP', 'CFLD_EXPPE', 'CFLD_EXPT', 'CFLD_HLRB', 'CFLD_HLRP', 'CFLD_HLRR', 'CFLD_EALB', 'CFLD_EALP', 'CFLD_EALPE', 'CFLD_EALT', 'CFLD_EALS', 'CFLD_EALR', 'CFLD_ALRB', 'CFLD_ALRP', 'CFLD_ALR_NPCTL', 'CFLD_RISKV', 'CFLD_RISKS', 'CFLD_RISKR']

In [29]:
# Inspect all Coastal Flood variables for counties with missing CFLD_RISKS

cfld_cols = [col for col in fema_data.columns if "CFLD" in col]

missing_cfld_counties = fema_data[
    fema_data["STCOFIPS"].isin(
        fema_filtered[
            fema_filtered["CFLD_RISKS"].isnull()
        ]["STCOFIPS"]
    )
]

print(
    missing_cfld_counties[
        ["COUNTY"] + cfld_cols
    ]
)

        COUNTY  CFLD_EVNTS  CFLD_AFREQ  CFLD_EXP_AREA  CFLD_EXPB  CFLD_EXPP  \
331    Gadsden         NaN         NaN            NaN        NaN        NaN
335   Hamilton         NaN         NaN            NaN        NaN        NaN
339  Highlands         NaN         NaN            NaN        NaN        NaN
343    Jackson         NaN         NaN            NaN        NaN        NaN
351    Madison         NaN         NaN            NaN        NaN        NaN
361    Osceola         NaN         NaN            NaN        NaN        NaN
365       Polk         NaN         NaN            NaN        NaN        NaN
372     Sumter         NaN         NaN            NaN        NaN        NaN

     CFLD_EXPPE  CFLD_EXPT  CFLD_HLRB  CFLD_HLRP  ... CFLD_EALPE  CFLD_EALT  \
331         NaN        NaN        NaN        NaN  ...        NaN        NaN
335         NaN        NaN        NaN        NaN  ...        NaN        NaN
339         NaN        NaN        NaN        NaN  ...        NaN        NaN
343         NaN        NaN        NaN        NaN  ...        NaN        NaN
351         NaN        NaN        NaN        NaN  ...        NaN        NaN
361         NaN        NaN        NaN        NaN  ...        NaN        NaN
365         NaN        NaN        NaN        NaN  ...        NaN        NaN
372         NaN        NaN        NaN        NaN  ...        NaN        NaN

     CFLD_EALS       CFLD_EALR  CFLD_ALRB  CFLD_ALRP CFLD_ALR_NPCTL  \
331        NaN  Not Applicable        NaN        NaN            NaN
335        NaN  Not Applicable        NaN        NaN            NaN
339        NaN  Not Applicable        NaN        NaN            NaN
343        NaN  Not Applicable        NaN        NaN            NaN
351        NaN  Not Applicable        NaN        NaN            NaN
361        NaN  Not Applicable        NaN        NaN            NaN
365        NaN  Not Applicable        NaN        NaN            NaN
372        NaN  Not Applicable        NaN        NaN            NaN

     CFLD_RISKV  CFLD_RISKS      CFLD_RISKR
331         NaN         NaN  Not Applicable
335         NaN         NaN  Not Applicable
339         NaN         NaN  Not Applicable
343         NaN         NaN  Not Applicable
351         NaN         NaN  Not Applicable
361         NaN         NaN  Not Applicable
365         NaN         NaN  Not Applicable
372         NaN         NaN  Not Applicable

[8 rows x 23 columns]

In [30]:
# Number of counties with CFLD_RISKS = 0
print("Counties with CFLD_RISKS = 0:")
print((fema_data["CFLD_RISKS"] == 0).sum())

# Distribution of CFLD_RISKS values
print("\nSummary of CFLD_RISKS:")
print(fema_data["CFLD_RISKS"].describe())

# Smallest non-missing values
print("\nSmallest CFLD_RISKS values:")
print(
    fema_data["CFLD_RISKS"]
    .dropna()
    .sort_values()
    .head(20)
)

Counties with CFLD_RISKS = 0:
64

Summary of CFLD_RISKS:
count    500.000000
mean      49.268000
std       30.177315
min        0.000000
25%       25.150000
50%       50.100000
75%       75.050000
max      100.000000
Name: CFLD_RISKS, dtype: float64

Smallest CFLD_RISKS values:
83      0.0
82      0.0
1964    0.0
84      0.0
3227    0.0
71      0.0
67      0.0
68      0.0
70      0.0
75      0.0
77      0.0
324     0.0
333     0.0
220     0.0
95      0.0
1862    0.0
73      0.0
359     0.0
371     0.0
360     0.0
Name: CFLD_RISKS, dtype: float64

In [31]:
# Florida counties with lowest coastal flood risk

print(
    fema_filtered[
        ["COUNTY", "CFLD_RISKS"]
    ]
    .sort_values("CFLD_RISKS")
    .head(20)
)

        COUNTY  CFLD_RISKS
0      Alachua         0.0
1        Baker         0.0
3     Bradford         0.0
11    Columbia         0.0
23      Hardee         0.0
28      Holmes         0.0
20      Glades         0.0
47      Orange         0.0
58    Seminole         0.0
60    Suwannee         0.0
46  Okeechobee         0.0
62       Union         0.0
6      Calhoun        21.2
32   Lafayette        22.0
66  Washington        22.4
35        Leon        23.4
40      Marion        24.6
24      Hendry        25.6
19   Gilchrist        25.8
37     Liberty        28.6

In [32]:
# Replace non-applicable Coastal Flood Risk values with 0
# FEMA classifies these counties as "Not Applicable" across all CFLD fields
# A value of 0 represents no meaningful coastal flood exposure

fema_filtered["CFLD_RISKS"] = (
    fema_filtered["CFLD_RISKS"].fillna(0)
)

# Verify missing values after cleaning
print("Missing values after cleaning:")
print(fema_filtered.isnull().sum())

# Check updated Coastal Flood Risk distribution
print("\nCFLD_RISKS summary:")
print(fema_filtered["CFLD_RISKS"].describe())

Missing values after cleaning:
STATE         0
STATEABBRV    0
COUNTY        0
STCOFIPS      0
POPULATION    0
CFLD_RISKS    0
HRCN_RISKS    0
SOVI_SCORE    0
RESL_SCORE    0
dtype: int64

CFLD_RISKS summary:
count    67.000000
mean     47.791045
std      38.073795
min       0.000000
25%       0.000000
50%      61.200000
75%      79.700000
max      99.600000
Name: CFLD_RISKS, dtype: float64

In [34]:
# =========================
# Final FEMA Data Quality Checks
# =========================

# 1. Check for duplicate rows
duplicates = fema_filtered.duplicated().sum()
print(f"Number of duplicate rows: {duplicates}")

# 2. Check for invalid population values
invalid_population = fema_filtered[
    fema_filtered["POPULATION"] <= 0
]
print(f"\nNumber of invalid population values: {len(invalid_population)}")

# 3. Summary statistics for selected numeric features
print("\nPopulation Summary:")
print(fema_filtered["POPULATION"].describe())

print("\nCoastal Flood Risk Summary:")
print(fema_filtered["CFLD_RISKS"].describe())

print("\nHurricane Risk Summary:")
print(fema_filtered["HRCN_RISKS"].describe())

print("\nSocial Vulnerability Summary:")
print(fema_filtered["SOVI_SCORE"].describe())

print("\nResilience Summary:")
print(fema_filtered["RESL_SCORE"].describe())

# 4. Check number of unique counties
num_counties = fema_filtered["STCOFIPS"].nunique()
print(f"\nNumber of unique counties: {num_counties}")

# 5. Final dataset shape
print("\nFinal dataset shape:")
print(fema_filtered.shape)

# 6. Final column check
print("\nColumns:")
print(fema_filtered.columns)

Number of duplicate rows: 0

Number of invalid population values: 0

Population Summary:
count    6.700000e+01
mean     3.209963e+05
std      5.002960e+05
min      6.344000e+03
25%      2.804250e+04
50%      1.296980e+05
75%      3.793040e+05
max      2.698679e+06
Name: POPULATION, dtype: float64

Coastal Flood Risk Summary:
count    67.000000
mean     47.791045
std      38.073795
min       0.000000
25%       0.000000
50%      61.200000
75%      79.700000
max      99.600000
Name: CFLD_RISKS, dtype: float64

Hurricane Risk Summary:
count    67.000000
mean     94.034832
std       5.467541
min      74.468085
25%      90.967877
50%      94.993742
75%      98.581560
max      99.958281
Name: HRCN_RISKS, dtype: float64

Social Vulnerability Summary:
count    67.000000
mean     57.781227
std      23.531667
min      11.386768
25%      40.362595
50%      56.679389
75%      75.445293
max      97.900763
Name: SOVI_SCORE, dtype: float64

Resilience Summary:
count    67.000000
mean     32.330238
std      23.003035
min       0.667939
25%      11.323155
50%      29.452926
75%      47.375954
max      96.278626
Name: RESL_SCORE, dtype: float64

Number of unique counties: 67

Final dataset shape:
(67, 9)

Columns:
Index(['STATE', 'STATEABBRV', 'COUNTY', 'STCOFIPS', 'POPULATION', 'CFLD_RISKS',
       'HRCN_RISKS', 'SOVI_SCORE', 'RESL_SCORE'],
      dtype='str')

In [35]:
# Save cleaned FEMA dataset
fema_filtered.to_csv(
    "../data/interim/cleaned_fema_data.csv",
    index=False
)

print("Cleaned FEMA dataset saved successfully.")

Cleaned FEMA dataset saved successfully.